### ISSUE TITLE
How to report invalid filter expression?

### ISSUE THREAD

**Issue by fathzer** [bohnman/squiggly#68]
I use squiggly in a SpringBoot web service.
When a client sends an invalid filtering expression, SquigglyParser sends a org.antlr.v4.runtime.misc.ParseCancellationException which is caught by Jackson, converted to a JSonMappingException and finally to a HttpMessageNotWritableException that results in a http 500 error ... which is very far from the problem.

First, I catched the HttpMessageNotWritableException in an ExceptionHandler, verify the root exception is a ParseCancellationException, and then return a 400 error code.

But looking an antlr exception, package also used by spring boot, seemed to me a dangerous option.
So, I created a SquigglyParser subclass with a parse method that catch that exception and throws a specific one. In my ExceptionHandler, if I detect it as a root exception of a HttpMessageNotWritableException, I return http 400 error.

My question is:
- Is there any cleaner/simpler way to detect wrong filtering expressions and return the expected 400 error code?

**Comment by bohnman** [comment]
In version 2 (not out yet), I have a custom exception.  However, in version 1, doing what you describe will work.

**Comment by fathzer** [comment]
Thanks a lot for the fast answer ... and for this very useful piece of code :-)
